CC = gcc
CFLAGS = -Wextra -Wall -Werror -std=c99 -pedantic -g3 -I ./src/

:
	@$(BINARY) -f $(DIR)$(MAKEFILE) alll
	@$(BINARY) -f $(DIR)$(MAKEFILE) clean

: yes

: $(DIR)test

: $(DIR)test.o
	$(CC) $(CFLAGS) -o $(DIR)test $(DIR)test.o

:
	$(CC) $(CFLAGS) -c -o $(DIR)test.o $(DIR)test.c

:
	rm -f $(DIR)test $(DIR)test.o
