CC = gcc
CFLAGS = -Wextra -Wall -Werror -std=c99 -pedantic -g3 -I ./src/

all:
	@$(BINARY) -f $(DIR)$(MAKEFILE) alll
	@$(BINARY) -f $(DIR)$(MAKEFILE) clean

alll: yes

FOO = $(BAR)
BAR = $(FOO)

yes:
	$(BAR)
