CC = gcc
CFLAGS = -Wextra -Wall -Werror -std=c99 -pedantic

all:
	@$(BINARY) -f $(DIR)$(MAKEFILE) alll
	@$(BINARY) -f $(DIR)$(MAKEFILE) clean

alll: yes

yes: $(DIR)test
	@

$(DIR)test: $(DIR)test.o
	@
	@
	$(CC) $(CFLAGS) -o $(DIR)test $(DIR)test.o

$(DIR)test.o:
	@
	$(CC) $(CFLAGS) -c -o $(DIR)test.o $(DIR)test.c
	@

clean:
	rm -f $(DIR)test $(DIR)test.o
