CC = gcc
CFLAGS = -Wextra -Wall -Werror -std=c99 -pedantic -g3 -I ./src/

all:
	@touch $(DIR)alll
	@$(BINARY) -f $(DIR)$(MAKEFILE) alll
	@$(BINARY) -f $(DIR)$(MAKEFILE) clean
	@$(BINARY) -f $(DIR)$(MAKEFILE) alll
	@$(BINARY) -f $(DIR)$(MAKEFILE) clean

alll: yes

yes: $(DIR)test

$(DIR)test: $(DIR)test.o
	$(CC) $(CFLAGS) -o $(DIR)test $(DIR)test.o

$(DIR)test.o: $(DIR)test.c
	$(CC) $(CFLAGS) -c -o $(DIR)test.o $(DIR)test.c

clean:
	rm -f $(DIR)test $(DIR)test.o $(DIR)alll

.PHONY: alll yes $(DIR)test $(DIR)test.o
