CC = gcc
CFLAGS = -Wextra -Wall -Werror -std=c99 -pedantic

all:
	@$(BINARY) -f $(DIR)$(MAKEFILE) alll
	@$(BINARY) -f $(DIR)$(MAKEFILE) clean

alll: yes

yes: $(DIR)test

$(DIR)test: $(DIR)test.o
	$(CC) $(CFLAGS) -o $@ $<

$(DIR)%.o: $(DIR)%.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(DIR)test $(DIR)test.o
