CC = gcc
CFLAGS = -Wextra -Wall -Werror -std=c99 -pedantic

all:
	@$(BINARY) -f $(DIR)$(MAKEFILE) alll

    $(         coucouc )alll: yes

A = 42
yes: $(   DIR       )test
	echo $(         A		)

test: $(            aifilhf   	)
